export const corpus = [
  "The cat sat on the mat",
  "I love programming in JavaScript",
  "Today is a sunny day",
  "She sells seashells by the seashore",
  "The quick brown fox jumps over the lazy dog",
  "I enjoy solving coding challenges",
  "He plays football on weekends",
  "They went to the market together",
  "Artificial intelligence is fascinating",
  "I drink coffee every morning",
  "My favorite color is blue",
  "We are learning about tokenization",
  "Birds are singing in the trees",
  "Can you pass me the salt please",
  "Reading books expands the mind",
  "Time flies when you are having fun",
  "I like to travel to new places",
  "Water is essential for life",
  "He works at a software company",
  "This cake tastes delicious",
  "Music can change your mood",
  "My phone battery is low",
  "The movie starts at eight",
  "I need to charge my laptop",
  "The train arrives at the station",
  "We will meet at the park",
  "Learning new skills is important",
  "Please close the window",
  "I am writing a new blog post",
  "Exercise keeps you healthy",
  "It is raining outside",
  "Do you want some tea",
  "He is fixing the car",
  "The flowers are blooming",
  "She is baking a cake",
  "We should clean the house",
  "I forgot my password again",
  "He bought a new bicycle",
  "She is wearing a red dress",
  "They are playing in the garden",
  "I am learning JavaScript today",
  "The book is on the table",
  "We went hiking last weekend",
  "I enjoy painting landscapes",
  "She is studying for exams",
  "The sun is shining bright",
  "He is watching a football match",
  "I have a meeting tomorrow",
  "Can you help me move this box",
  "The baby is sleeping peacefully",
  "I am reading an interesting novel",
  "They are visiting the museum today",
  "He found a wallet on the street",
  "Please bring me a glass of water",
  "I am making a cup of tea",
  "We will start the project soon",
  "She is speaking at the conference",
  "I lost my keys yesterday",
  "The river flows through the valley",
  "He likes to swim in the ocean",
  "We are building a treehouse",
  "The sky is full of stars",
  "I like spicy food",
  "She enjoys playing the piano",
  "They are planting trees in the park",
  "I have to wake up early tomorrow",
  "We will visit the zoo this weekend",
  "The streets are empty at night",
  "I am learning how to cook",
  "The dog is barking loudly",
  "He is repairing the bike",
  "We are going to the beach",
  "I need to water the plants",
  "The lights are flickering",
  "She is listening to music",
  "He is drawing a picture",
  "I am writing an email",
  "We are preparing for the trip",
  "The mountain is covered in snow",
  "I am learning to drive",
  "She is dancing gracefully",
  "He is cooking dinner tonight",
  "The bus stops near my house",
  "I need to buy some groceries",
  "We are having lunch together",
  "The wind is blowing strongly",
  "I am fixing the computer",
  "She is playing with her cat",
  "We will start the meeting soon",
  "The child is laughing happily",
  "I am studying web development",
  "They are painting the walls",
  "He is running in the park",
  "I need to clean my room",
  "We are working on a new project",
  "The phone is ringing loudly",
  "I am sending a message",
  "She is reading a magazine",
  "He is wearing a black jacket",
  "We are watching a movie",
  "The stars are shining brightly",
  "I am feeling very tired today",
  "Anurag dubey",

  // Added: Developer & tech phrases
  "I am debugging the code",
  "Push the changes to the repository",
  "The server is down right now",
  "We deployed the app to production",
  "I am learning how to use React",
  "Next.js provides both SSR and SSG",
  "Prisma makes database queries easier",
  "This API returns JSON data",
  "The frontend is built with TypeScript",
  "Please commit your changes before pushing",
  "The request timed out after 30 seconds",
  "I created a pull request on GitHub",
  "Run npm install to install dependencies",
  "Our database is hosted on NeonDB",
  "Clerk handles authentication for our app",

  // Added: Numbers, dates, and times
  "I was born on January 5, 1995",
  "The event starts at 7:30 PM",
  "She scored 95 marks in the exam",
  "The temperature is 27 degrees Celsius",
  "We will meet at 10 AM tomorrow",
  "It costs $25 to enter the park",
  "My phone number is 9876543210",
  "The package weighs 2.5 kilograms",

  // Added: Special characters & punctuation
  "Hello, world!",
  "What's your name?",
  "Email me at test@example.com",
  "The file path is C:\\Users\\Admin",
  "Use the command: git pull origin main",
  "He said, 'I will be there soon.'",
  "This is a test... just a test!",
  "Can you solve 2 + 2 = 4?",

  // Added: Random extra sentences for vocab variety
  "The clouds are moving fast",
  "I need to book a flight ticket",
  "We watched fireworks last night",
  "He adopted a puppy from the shelter",
  "The library is closed on Sundays",
  "Please turn off the lights",
  "She forgot to lock the door",
  "The bus driver is on a break",
  "I love eating mangoes in summer",
  "They are discussing the project deadline",
  "The kids are playing in the rain",
  "I just finished my homework",
  "The shop opens at 9 AM",
  "I met my friend after five years",
  "The cake is in the fridge",
  "I can't find my headphones",
  "The alarm clock didn't ring",
  "We are learning about machine learning",
  "The email was marked as spam",
  "Here are some special characters: ()>_-*&^%#|`~/;<",
];
